function crgPath = scn_export_opencrg(scenario, outDir, opts)
%SCN_EXPORT_OPENCRG 노면 elevation (z_road) → ASAM OpenCRG (.crg) 파일 export
%
%   OpenCRG 1.2 minimal ASCII format을 자체 writer로 생성 (외부 라이브러리 없음).
%
%   포맷 요약 (ASAM OpenCRG 1.2 §5):
%     $ROAD_CRG          (시작 마커)
%     reference_line_*   (도로 중심선)
%     ...
%     $KD_Definition     (격자 정의)
%     #:    longitudinal increment (m)
%     ...
%     $$$$$$$$$$
%     <binary or ASCII grid data>
%
%   본 구현은 **단순화된 ASCII v1.2**: 도로를 (s, t) 격자로 분할 + z(s,t) 값.

    if nargin < 2 || isempty(outDir)
        outDir = fullfile(pwd, 'data', 'scenarios_export');
    end
    if ~exist(outDir,'dir'); mkdir(outDir); end
    if nargin < 3; opts = struct(); end
    if ~isfield(opts,'roadLength');  opts.roadLength = 200; end
    if ~isfield(opts,'lateralWidth'); opts.lateralWidth = 4.0; end   % ±2 m

    crgPath = fullfile(outDir, [scenario.id '.crg']);

    % Sampling: 0.1m longitudinal × 0.5m lateral
    ds_lon = 0.1; ds_lat = 0.5;
    s = (0:ds_lon:opts.roadLength)';
    t_lat = (-opts.lateralWidth/2 : ds_lat : opts.lateralWidth/2);
    [S, T] = ndgrid(s, t_lat);
    Z = zeros(size(S));

    % z_road(t,wheel) — 시간함수를 공간함수로 변환 (vx0 가정)
    vx = scenario.vx0;
    for is = 1:size(S,1)
        time_at_s = s(is) / vx;
        if time_at_s > scenario.tEnd; continue; end
        % all 4 wheels probe — average for the strip
        z_at_s = 0;
        for w = 1:4
            z_at_s = z_at_s + scenario.z_road(time_at_s, w);
        end
        z_at_s = z_at_s / 4;
        Z(is, :) = z_at_s;   % uniform across lateral (simplification)
    end

    %% Write OpenCRG ASCII (simplified v1.2)
    fid = fopen(crgPath, 'w');
    fprintf(fid, '$ROAD_CRG\n');
    fprintf(fid, '$$$$$$$$$$\n');
    fprintf(fid, 'reference_line_start_u    = 0.0\n');
    fprintf(fid, 'reference_line_increment  = %.4f\n', ds_lon);
    fprintf(fid, 'long_section_v_right      = %.4f\n', t_lat(1));
    fprintf(fid, 'long_section_v_left       = %.4f\n', t_lat(end));
    fprintf(fid, 'long_section_v_increment  = %.4f\n', ds_lat);
    fprintf(fid, '$$$$$$$$$$\n');
    fprintf(fid, '$CT_DATA\n');
    fprintf(fid, '! Generated by ICC project scn_export_opencrg.m\n');
    fprintf(fid, '! Scenario: %s (%s)\n', scenario.id, scenario.name);
    fprintf(fid, '! Date: %s\n', datestr(now));
    fprintf(fid, '$$$$$$$$$$\n');
    fprintf(fid, '$KD_DEFINITION\n');
    fprintf(fid, '#:  long_section %d %.4f\n', size(S,1), ds_lon);
    fprintf(fid, '#:  cross_section %d %.4f %.4f\n', size(S,2), t_lat(1), ds_lat);
    fprintf(fid, '$$$$$$$$$$\n');
    fprintf(fid, '$ROAD_CRG_DATA\n');
    % Write Z grid in row-major (each longitudinal row contains all lateral values)
    for is = 1:size(Z,1)
        fprintf(fid, '%.6e ', Z(is,:));
        fprintf(fid, '\n');
    end
    fprintf(fid, '$ROAD_CRG_END\n');
    fclose(fid);

    fprintf('  [scn_export_opencrg] %s — grid %dx%d, max|z|=%.3f mm\n', ...
        crgPath, size(Z,1), size(Z,2), max(abs(Z(:)))*1000);
end
